- name: Get current workflow job ID
  hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        var: ansible_env
      delegate_to: localhost
        
    - set_fact:
        job_id: "{{ lookup('env', 'awx_workflow_job_id') | int }}"
  
    - name: Show the workflow job ID
      debug:
        msg: "Current Workflow Job ID is {{ job_id }}"
