---
- name: Export AWX Activity Stream Logs
  hosts: localhost
  gather_facts: true
  vars:
    tower_host: "https://awx.example.com"
    tower_username: "admin"
    tower_password: "admin123"
    output_file: "activity_stream.json"

  tasks:
    - name: Ensure host entry is present
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.1.12    awx.example.com"
        state: present
        unsafe_writes: true
        create: yes

    - name: Get activity stream logs
      ansible.builtin.uri:
        url: "{{ tower_host }}/api/v2/activity_stream/?page_size=1000"
        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        validate_certs: false
        return_content: yes
      register: activity_stream

   # - name: Added debug for testing
   #   ansible.builtin.debug:
   #     msg: "{{ activity_stream }}"
#    - name: Save activity stream logs to file
#      copy:
#        content: "{{ activity_stream.content }}"
#        dest: "{{ output_file }}"

    - name: Generate HTML Activity Report using Jinja2
      ansible.builtin.template:
        src: activity_report.j2
        dest: /tmp/activity_report.html

    - name: Email Alert if fail server is unreachable
#      when: ping_result.unreachable is defined
      mail:
        host: smtp.gmail.com
        port: 587
        subtype: html
        to:
        - "nrathi@redhat.com"
        subject: "Alert: Activity Report for AWX"
        body: "{{ lookup('file', '/tmp/activity_report.html') }}"
        username: "dmeonavneet@gmail.com"
        password: "rbfqhoincpyouxqk"
      run_once: true  
      delegate_to: 127.0.0.1
      changed_when: True   
