- name: Get current workflow job ID
  hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        var: ansible_env
      delegate_to: localhost
        
    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"
  
    - name: Show the workflow job ID
      debug:
        msg: "Current Workflow Job ID is {{ job_id }}"
        
    - set_fact:
        job_api: "{{ lookup('ansible.controller.controller_api', 'jobs/{{ job_id }}', host='aap.example.org',
                                  username='admin', password='primod123', verify_ssl=False) }}"
        
    - debug:
        var: job_api
      
