---
- name: Generate Last 1 Month Job Report
  hosts: aux_server
  become: true
  gather_facts: true
  vars:
    controller_url: "https://192.168.64.63"
    tower_username: "admin"
    tower_password: "primod123"
    # Calculate date 30 days ago in ISO format (YYYY-MM-DD)
    last_month: "{{ lookup('pipe', 'date -d \"30 days ago\" +%Y-%m-%d') }}"
    page_size: 200

    tasks:
    - name: Fetch first page of jobs
      ansible.builtin.uri:
        url: "{{ controller_url }}/api/controller/v2/jobs/?finished__gte={{ last_month }}&order_by=-finished&page_size={{ page_size }}"
        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        validate_certs: false
      register: first_page

    - name: Calculate total pages
      ansible.builtin.set_fact:
        total_pages: "{{ (first_page.json.count / page_size) | round(0, 'ceil') | int }}"

    - name: Fetch remaining pages
      ansible.builtin.uri:
        url: "{{ controller_url }}/api/controller/v2/jobs/?finished__gte={{ last_month }}&order_by=-finished&page_size={{ page_size }}&page={{ item }}"
        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: yes
        validate_certs: false
      # Loop from page 2 to the end
      loop: "{{ range(2, total_pages | int + 1) | list }}"
      register: remaining_pages
      when: total_pages | int > 1

    - name: Consolidate all results
      ansible.builtin.set_fact:
        all_jobs: >-
          {{ 
            first_page.json.results + 
            (remaining_pages.results | default([]) | map(attribute='json.results') | flatten) 
          }}

    - name: Generate HTML Report
      ansible.builtin.template:
        src: report_template.j2
        dest: "/usr/share/nginx/html/job_report_{{ ansible_date_time.date }}.html"
      vars:
        jobs: "{{ all_jobs }}"
        report_title: "Monthly Automation Summary"
        report_range: "Last 30 Days (Since {{ last_month }})"
    
    - name: Convert the HTML file to PDF
#    ansible.builtin.command:
      ansible.builtin.shell: "/usr/local/bin/wkhtmltopdf /usr/share/nginx/html/job_report_{{ ansible_date_time.date }}.html /usr/share/nginx/html/job_report_{{ ansible_date_time.date }}.pdf"
        #creates: "/tmp/output.pdf" # This prevents the task from running if the output file already exists

 